[theme]
primaryColor            = "#2DAD7E"
backgroundColor         = "#0A0A0A"
secondaryBackgroundColor = "#111111"
textColor               = "#FFFFFF"
font                    = "sans serif"

[server]
maxUploadSize = 10
headless      = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
